### ISSUE TITLE
HTTP 404 Error

### ISSUE THREAD

**Issue by famasoon** [evyatar9/GptHidra#9]
Version: latest(gpt-4 version)
ghidra: version : 11.2.1
I run this command, but this error occured

```
gptghidra.py> Running...
Traceback (most recent call last):
  File "C:\Users\sakai\ghidra_scripts\gptghidra.py", line 75, in <module>
    explanation = explainFunction(c_code)
  File "C:\Users\sakai\ghidra_scripts\gptghidra.py", line 75, in <module>
    explanation = explainFunction(c_code)
  File "C:\Users\sakai\ghidra_scripts\gptghidra.py", line 34, in explainFunction
    response = json.loads(urllib2.urlopen(req).read())
  File "C:\Users\sakai\Downloads\ghidra_11.2.1_PUBLIC_20241105\ghidra_11.2.1_PUBLIC\Ghidra\Features\Jython\lib\jython-standalone-2.7.3.jar\Lib\urllib2.py", line 154, in urlopen
  File "C:\Users\sakai\Downloads\ghidra_11.2.1_PUBLIC_20241105\ghidra_11.2.1_PUBLIC\Ghidra\Features\Jython\lib\jython-standalone-2.7.3.jar\Lib\urllib2.py", line 435, in open
  File "C:\Users\sakai\Downloads\ghidra_11.2.1_PUBLIC_20241105\ghidra_11.2.1_PUBLIC\Ghidra\Features\Jython\lib\jython-standalone-2.7.3.jar\Lib\urllib2.py", line 547, in http_response
  File "C:\Users\sakai\Downloads\ghidra_11.2.1_PUBLIC_20241105\ghidra_11.2.1_PUBLIC\Ghidra\Features\Jython\lib\jython-standalone-2.7.3.jar\Lib\urllib2.py", line 473, in error
  File "C:\Users\sakai\Downloads\ghidra_11.2.1_PUBLIC_20241105\ghidra_11.2.1_PUBLIC\Ghidra\Features\Jython\lib\jython-standalone-2.7.3.jar\Lib\urllib2.py", line 407, in _call_chain
  File "C:\Users\sakai\Downloads\ghidra_11.2.1_PUBLIC_20241105\ghidra_11.2.1_PUBLIC\Ghidra\Features\Jython\lib\jython-standalone-2.7.3.jar\Lib\urllib2.py", line 556, in http_error_default
urllib2.HTTPError: HTTP Error 404: Not Found
gptghidra.py> Finished!
```

How to fix it?
or more information, I will provide you

**Comment by famasoon** [comment]
Sorry,  I retry it, do not show error.
maybe network is unstable, so I will close this issue

**Comment by evyatar9** [comment]
Hi @famasoon famasoon ,

I just checked for GptHidra-GPT-4, and it works.  
Can you write down the link the code is trying to access?

Thanks!

**Comment by evyatar9** [comment]
> Sorry, I retry it, do not show error. maybe network is unstable, so I will close this issue

Oh, Great! :)
